version: "3.9"

services:
  db:
    image: postgres:13.4
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rubyandrails_info_development
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/rubyandrails_info_development
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - bundle:/usr/local/bundle
    command: ["rails", "server", "-b", "0.0.0.0"]

volumes:
  db_data:
  node_modules:
  bundle:
